-- 插入系统测试数据SQL脚本
-- Version: 1.1
-- Time: 2018年1月17日
-- Run: SQL Server2012
-- To：SQL 2008R2+
-- By: Jiuone

--切换数据库
use NineCode
go


--用户表数据
insert into Users values('admin','123456','50966256@qq.com',default,default)
insert into Users values('test','123456','50966256@qq.com',default,default)
insert into Users values('user','123456','50966256@qq.com',default,'false')
insert into Users values('guest','123456',null,default,default)
--
select * from Users
select upper(substring(sys.fn_sqlvarbasetostr(HashBytes('MD5','123456')),3,32))

--网站分类数据
insert into Category values('未分类')
insert into Category values('前端技术')
insert into Category values('数据库技术')
insert into Category values('.Net技术')
insert into Category values('框架使用')

--
select * from Category



--标签表数据
insert into Tag values('HTML')
insert into Tag values('CSS')
insert into Tag values('JavaScript')
insert into Tag values('WinForm')
insert into Tag values('Asp.Net')
insert into Tag values('Ado.Net')

--
select * from Tag


--文章表数据
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,100)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,100)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,101)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,100)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,102)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,101)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,103)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,102)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,100)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,101)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,100)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,103)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,100)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,102)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,100)
insert into Article values('测试文章标题','<ul class="lead"><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li><li><a href="http//:www.jiuone.cn" target="_blank">我是一条不错的 -- 2018年1月16日</a></li></ul>',default,10000,101)

--
select * from Article


--关系表数据
insert into Relation values(10000,104)
insert into Relation values(10001,103)
insert into Relation values(10002,102)
insert into Relation values(10003,101)
insert into Relation values(10004,100)
insert into Relation values(10005,101)
insert into Relation values(10006,102)
insert into Relation values(10007,103)
insert into Relation values(10008,104)
insert into Relation values(10009,103)
insert into Relation values(10010,102)
insert into Relation values(10011,101)
insert into Relation values(10012,100)

--
select * from Relation


--网站基本信息数据
insert into SiteInfo values('NineCode','程序猿的代码库！','NideCode,NineCMS,Jiuone,ninecms.com','鄂ICP备000001号','网安备4200000号','<script src="https://s4.cnzz.com/z_stat.php?id=1260990323&web_id=1260990323" language="JavaScript"></script>',default,'网站更新维护，暂时暂停服务！')

--
select * from SiteInfo




--网站配置数据
insert into SiteConfig values('smtp.mxhichina.com',80,'test@ninecms.com','Jiuone75494','test@ninecms.com')

--
select * from SiteConfig
